### ISSUE TITLE
SVN::Hooks::UpdateConfFile - UPDATE_CONF_FILE not copying svn-hooks.conf from repository after commit

### ISSUE THREAD

**Issue by mat060** [gnustavo/SVN-Hooks#7]
Hello,

I’m having a hard time configuring my hooks combining the __pre-commit__ and __svn-hooks.conf__ approach, I created the svn-hooks.conf file and added it to the repository and the committed the changes.

I’m then creating the pre-commit script into the hooks directory and giving it execution permissions, but after I commit any changes to the repository I don’t the file created in the conf folder in the server. I’m wondering if it has something to do with the repository path in which I’m storing the svn-hooks.conf file, which is different than the suggested conf folder

The script pre-commi seems to be executing properly since I don’t get any errors during any commit client operation, It just seems not to do anything when calling UPDATE_CONF_FILE

# svn-hooks.conf 
at /path_to_repo/conf
```perl
use SVN::Hooks;
use SVN::Hooks::DenyFilenames;

DENY_FILENAMES([qr/[^-\_\.\w]/i => 'Invalid file name. Only the following characters are allowed: a-z, A-Z, 0-9, -, _ and .']);

1; #required for do{} success
```

# pre-commit
at /path_to_repo/hooks
```perl
#!/usr/bin/perl

use SVN::Hooks;
use SVN::Hooks::UpdateConfFile;
use SVN::Hooks::DenyFilenames;

UPDATE_CONF_FILE(
    'SomePath/UnderVersionControl/Scripts/svn/svn-hooks.conf' => 'svn-hooks.conf',
    validator => [qw(/usr/bin/perl -c)],
    rotate => 2,
);

run_hook($0, @ARGV);
```

**Comment by gnustavo** [comment]
Hi Angel,

I got your email, but I'm answering it here to make it potentially more useful.

To your specific questions:

* Should I copy the svn-hooks.conf within the svn/repo/conf folder (in the server side) before it starts working for the first time (before I even commit the conf file to the repository?

Yes. Otherwise the hook won't be configured and it won't install it's own configuration using the UPDATE_CONF_FILE directive.

* Should I include the library to the UPDATE_CONF_FILE within the svn-hooks.conf file?

You can, but I normally put all non-secret (i.e. passwords) directives in the svn-hooks.conf file.

* How can I trace the UPDATE_CONF_FILE perl execution to see where is the script exiting without doing anything.

There's no provision for tracing, but you can make the hooks run under the Perl debugger by passing  the -d option to Perl in the hook scripts like this:

> #!/usr/bin/perl -d

This only works if you use the svn command with a file:// URL poiting to the repository, so that the server-side of Subversion runs in the same process as the client side.

* Does the FROM path supports paths within the repository other than conf/, something like server/scripts/svn/svn-hooks.conf

Yes. The problem with your set up is that UPDATE_CONF_FILE takes effect in two hooks: pre-commit and post-commit. In the pre-commit it validates the file and in the post-commit it makes the actual copying and rotation.

* In the documentation I see an extra comma after the rotate => 2 line, is this right?

Yes. Perl lets you end your lists with a comma, which is handy when you put each element of the list on one line. (See [this](https://metacpan.org/pod/Perl::Critic::Policy::CodeLayout::RequireTrailingCommas).)

* Do you have a sample of a working pair of svn-hooks.conf and svn-hooks.pl (actual files) that you can share as reference?

Sure. Download [this shellscript](https://gist.github.com/gnustavo/565674ef0dbaea15def9), take a look a it and run it under a new directory you created on purpose. It will create a repository, set up your hooks, and perform some tests. I hope it makes it clear how to go about it.

The main differences to what you've done are the following:
* There is a single hook script (repo/hooks/svn-hooks.pl) to which all hooks refer to as symlinks.
* It installs two hooks: pre-commit and post-commit.
* All configuration is on the svn-hooks.conf file.
* The DENY_FILENAMES must accept slashes (/) because it checks the complete path of the files.

Just a warning: the conf/svn-hooks.conf is a Perl script that will be executed on the server. So, you should be very careful not to let unintended users to change it, since you are versioning it under the same repository. I do this too, but I have an authz file set up to let only a few selected users write under the versioned 'conf' directory.

**Comment by mat060** [comment]
Hi Gustavo,

Thanks for answering so quick. I have a couple more questions based on your responses from above:

> __QUESTION:__ Should I copy the svn-hooks.conf within the svn/repo/conf folder (in the server side) before it starts working for the first time (before I even commit the conf file to the repository?

> __ANSWER:__ Yes. Otherwise the hook won't be configured and it won't install it's own configuration using the UPDATE_CONF_FILE directive.

__ADDITIONAL QUESTION:__ How would this work when using the argument remove = true?, my understanding is that the svn-hooks.conf file would be removed from the conf folder  if the svn-hooks.conf file is removed from version control. If the svn-hooks.conf file is ever put back into version control, would the script be restored in the conf folder autmatically by UPDATE_CONF_FILE or the remove action is permanent and have to manually put the svn-hooks.conf file before it can be recognized by the UPDATE_CONF_FILE in pre-commit and post-commit scripts?

For your comment:
> The DENY_FILENAMES must accept slashes (/) because it checks the complete path of the files.

Thanks for the heads up, I noticed that not allowing the slash (/) is an issue only when committing new folders, the files where being committed properly even though the slash was not allowed.
I only have to test my new regex __/[^\w\/\ \-\.]/i__ from different systems (windows/linux/macos) to ensure no one is going to commit a file with a slash in the actual file name, I don't want to have a file named file/with/slashes.txt committed to SVN by mistake.

__Can I suggest to update the documentation__ for the current or the next release with the notes we produced here? It would be very helpful for people like my with high expectation requirements but low skills in SVN hooks :smile:

**Comment by mat060** [comment]
And off course I'm rude.. I forgot to mention that all your comments helped me out very well. I now have my pre-commit- post-commit and svn-hooks.conf working perfectly and getting updates from the repository.

Thank you very much!

**Comment by mat060** [comment]
Update on the slash validation from Mac OSX.

Mac OS (El Capitan) lets you create a file with a slash in the name no problem, for example __test/file.txt__

Fortunately for this test, a couple of clients, SnailSVN and Cornerstone see the file with a colon instead of a slash, producing an error due the colon, since it is not an character allowed by the DENY_FILENAMES plugin.

Windows doesnt seem to be a problem since slash is not allowed in file names in Windows.

I can now relax and enjoy user not committing files with potentially non-multi-platform names.

Thank you very much Gustavo.

# SnailSVN
![screenshot 2016-01-27 20 32 08](https://cloud.githubusercontent.com/assets/16904216/12633228/5127bbbc-c535-11e5-864a-8b0500cae37c.png)
![screenshot 2016-01-27 20 32 29](https://cloud.githubusercontent.com/assets/16904216/12633230/5602b2ea-c535-11e5-982b-2a41ddf8ed73.png)
![screenshot 2016-01-27 20 33 04](https://cloud.githubusercontent.com/assets/16904216/12633231/598df9ce-c535-11e5-833e-b75009744257.png)
![screenshot 2016-01-27 20 33 17](https://cloud.githubusercontent.com/assets/16904216/12633233/5c943142-c535-11e5-9659-e4eb15e05737.png)

# Cornerstone
![screenshot 2016-01-27 20 35 34](https://cloud.githubusercontent.com/assets/16904216/12633253/8b649c00-c535-11e5-8711-211adf2bd698.png)
![screenshot 2016-01-27 20 39 20](https://cloud.githubusercontent.com/assets/16904216/12633303/17d5173c-c536-11e5-8fea-2b771b2153e7.png)

# Windows
![screenshot 2016-01-27 20 43 22](https://cloud.githubusercontent.com/assets/16904216/12633353/a7b73cd6-c536-11e5-82ad-4e5ccee7a78d.png)

**Comment by gnustavo** [comment]
Hi Angel,

I'm glad to know that you're up and running with SVN::Hooks!

As for your...

> __ADDITIONAL QUESTION:__ How would this work when using the argument remove = true?, my understanding is that the svn-hooks.conf file would be removed from the conf folder  if the svn-hooks.conf file is removed from version control. If the svn-hooks.conf file is ever put back into version control, would the script be restored in the conf folder autmatically by UPDATE_CONF_FILE or the remove action is permanent and have to manually put the svn-hooks.conf file before it can be recognized by the UPDATE_CONF_FILE in pre-commit and post-commit scripts?

If it were any other file it would be restored but the svn-hooks.conf contains the very instructions telling SVN::Hooks what to do. So, if it's removed the hooks stop working.

I'll try to incorporate this discussion in the documentation as you suggested.

Thanks!
